# Generated by Django 5.0.2 on 2024-02-17 22:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionaries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Hotel Name", max_length=3000, verbose_name="Name"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Hotel Address",
                        max_length=3000,
                        verbose_name="Address",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Hotel Phone Number",
                        max_length=128,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="Hotel City",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dictionaries.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotels",
                "verbose_name_plural": "Hotels",
            },
        ),
    ]
