# Generated by Django 5.0.2 on 2024-02-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0001_initial"),
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hotels",
            new_name="Hotel",
        ),
    ]
